[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.env]
NODE_VERSION = "18"
PORT = "3000"
REACT_APP_API_URL = "https://tinywins.up.railway.app"
NODE_ENV = "production" 
